all: maximo complejo rectangulo assert_ex iteradores rectangulo_ex1 rectangulo_constructores complejo_amiga

complejocamiga:
	g++ complejo_amiga.cpp -o complejo_amiga

maximo:
	g++ maximo.cpp -o maximo

complejo:
	g++ complejo.cpp -o complejo

rectangulo:
	g++ rectangulo.cpp rectangulo.hpp -o rectangulo

rectangulo_ex1:
	g++ rectangulo_ex1.cpp -o rectangulo_ex1

rectangulo_constructores:
	g++ rectangulo_constructores.cpp -o rectangulo_constructores

assert_ex:
	g++ assert_ex.cpp -o assert_ex

iteradores:
	g++ iteradores.cpp -o iteradores

clean:
	rm -f maximo complejo rectangulo assert_ex1 iteradores rectangulo_ex1 rectangulo_constructores